---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - role::icinga2_agent
    - role::icinga2_agent:install

- name: Set packages enable repo
  ansible.builtin.set_fact:
    icinga2_agent_packages_enablerepo: "{{ icinga2_agent_packages_enablerepo_override }}"
  when:
    - icinga2_agent_packages_enablerepo_override | length > 0
    - ansible_os_family == 'RedHat'
  tags:
    - role::icinga2_agent
    - role::icinga2_agent:install

- name: Set packages list
  ansible.builtin.set_fact:
    icinga2_agent_packages: "{{ icinga2_agent_packages_override }}"
  when:
    - icinga2_agent_packages_override | length > 0
    - ansible_os_family == 'RedHat'
  tags:
    - role::icinga2_agent
    - role::icinga2_agent:install

- name: Import installation tasks
  ansible.builtin.import_tasks: installation.yml
  tags:
    - role::icinga2_agent
    - role::icinga2_agent:install
