---
name: CI - Linting

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: icinga2_agent

      # Checkout Adfinis lint-rules
      - uses: actions/checkout@v2
        with:
          repository: adfinis/ansible-lint-rules
          path: lint-rules

      - name: Install Ansible-Galaxy Requirements
        run: ansible-galaxy install -r icinga2_agent/requirements.yml
      - name: ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          targets: icinga2_agent
          args: "-R -r lint-rules"
          override-deps: |
            ansible~=2.10
            ansible-lint~=6.0
      - name: yamllint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_config_filepath: icinga2_agent/.testenv/yamllint.yml
          yamllint_file_or_dir: icinga2_agent
